### ISSUE TITLE
Update search bars to match Community styling

### ISSUE THREAD

**Issue by AmNotADev** [do-community/do-bulma#5]
The current search bars came from the wrong styling, an error on my part. The new search bars should be styled as shown in [this Figma file](https://www.figma.com/file/gjpH9LfXpQ5OSQjrY8nrxt/Tooling-Search-Bars?node-id=0%3A1).

There's 4 "types" and two use-cases (white and light grey).

**Comment by MattIPv4** [comment]
A few questions about this (community stuff is all on white):

1. The mock has no box-shadow on the input, is that intentional? Imo, it looks odd:
![image](https://user-images.githubusercontent.com/12371363/69659481-30da0000-1076-11ea-80d1-fcd5eb792fba.png)

2. Could I get a mock for the focus state? This is the current style:
![image](https://user-images.githubusercontent.com/12371363/69659525-4818ed80-1076-11ea-90ba-6cb124d8db8f.png)

3. Should a button stacked below, but not part of, the search component also be given the box-shadow?
![image](https://user-images.githubusercontent.com/12371363/69659594-726aab00-1076-11ea-91bc-9da2a21c7465.png)
